<?php include __DIR__ . '/../header.html' ?>
    <div class="container">
        <div class="row">
            <h3>Listagem de categorias</h3>
            <a href="/categories/create">Nova categoria</a>
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Category</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html' ?>